### 对HMM进行验证 

In [1]:
import numpy as np
import HMM as _HMM
import HMMmodel as _HMM_

### Markov chain的生成 

《统计学习方法》例10.1——马尔可夫链的生成

In [2]:
A=np.array([[0,1,0,0],[0.4,0,0.6,0],[0,0.4,0,0.6],[0,0,0.5,0.5]])
B=np.array([[0.5,0.5],[0.3,0.7],[0.6,0.4],[0.8,0.2]])
pi=np.array([0.25,0.25,0.25,0.25])
hmm_1=_HMM.HMM(A,B,pi)

In [ ]:
# step=5
lat_type=[1,2,3,4]
obs_type=['red','white']

In [4]:
hmm_1.generate(step,lat_type,obs_type)

([2, 1, 2, 3, 4], ['red', 'white', 'white', 'red', 'red'])

### 前向传播算法评估

《统计学习方法》例10.2——前向算法求解评估问题

In [5]:
A=np.array([[0.5,0.2,0.3],[0.3,0.5,0.2],[0.2,0.3,0.5]])
B=np.array([[0.5,0.5],[0.4,0.6],[0.7,0.3]])
pi=np.array([0.2,0.4,0.4])
hmm_2=_HMM.HMM(A,B,pi)

In [6]:
step=3
obs=[0,1,0]
obs=np.array(obs)
#观测变量中，0代表红色，1代表白色

In [7]:
np.exp(hmm_2.log_likelihood(obs))

array([0.130218, 0.130218])

### 维特比算法评估

《统计学习方法》例10.3——维特比算法求解解码问题

In [8]:
pro,path=hmm_2.viterbi(obs)
print(pro)
print(path)

0.014700000000000036
[2, 2, 2]


### 使用EM算法学习HMM参数

测试用于学习问题的鲍姆-韦尔奇算法  
思路：人为设定参数A、B、pi产生有限个观测序列，并用HMM去fit这些观测序列，比较模型参数与实际参数

In [9]:
A=np.array([[0.7,0.2,0.1],[0.1,0.9,0],[0.2,0.3,0.5]])
B=np.array([[1,0],[0.1,0.9],[1,0]])
pi=np.array([0.2,0.4,0.4])
hmm_3=_HMM.HMM(A,B,pi)
step=20
lat_type=[0,1,2]
obs_type=[0,1]
O=[]
for i in range(100):
    _,obs=hmm_3.generate(step,lat_type,obs_type)
    O.append(obs)
O=np.array(O)

In [10]:
hmm_3.fit(O,lat_type,obs_type)

[0.33333333 0.33333333 0.33333333]
[[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]]
[[0.39186172 0.60813828]
 [0.09756335 0.90243665]
 [0.34706331 0.65293669]]
[[0.35265692 0.30234474 0.34499834]
 [0.31143712 0.36844757 0.32011531]
 [0.34653839 0.31215682 0.34130479]]
[Epoch 1] log_likelihood: -2697.581 Delta: 191.19551
[[0.36038398 0.29008782 0.3495282 ]
 [0.28217266 0.41930743 0.29851991]
 [0.3496222  0.30731835 0.34305945]]
[Epoch 2] log_likelihood: -2675.716 Delta: 21.86530
[[0.36769817 0.27911916 0.35318267]
 [0.25550771 0.46782123 0.27667106]
 [0.35276072 0.30274742 0.34449186]]
[Epoch 3] log_likelihood: -2647.697 Delta: 28.01888
[[0.37684585 0.26602277 0.35713139]
 [0.22795114 0.51953241 0.25251645]
 [0.35729091 0.29637373 0.34633536]]
[Epoch 4] log_likelihood: -2605.195 Delta: 42.50184
[[0.38916126 0.24909986 0.36173888]
 [0.19693118 0.57929021 0.22377862]
 [0.36396647 0.28719007 0.34884346]]
[Epoch 5] log_likelihood: 

[Epoch 50] log_likelihood: -2176.234 Delta: 0.04806
[[0.4637237  0.12614603 0.41013027]
 [0.05220161 0.89227139 0.055527  ]
 [0.44346936 0.15236749 0.40416315]]
[Epoch 51] log_likelihood: -2176.185 Delta: 0.04888
[[0.46426947 0.12600384 0.40972669]
 [0.05218485 0.89225173 0.05556343]
 [0.4435714  0.15265177 0.40377683]]
[Epoch 52] log_likelihood: -2176.136 Delta: 0.04961
[[0.46481492 0.12586313 0.40932196]
 [0.05216829 0.89223177 0.05559994]
 [0.44366982 0.1529371  0.40339309]]
[Epoch 53] log_likelihood: -2176.086 Delta: 0.05026
[[0.46535943 0.12572398 0.40891659]
 [0.05215197 0.89221153 0.0556365 ]
 [0.44376454 0.15322313 0.40301234]]
[Epoch 54] log_likelihood: -2176.035 Delta: 0.05083
[[0.46590239 0.12558651 0.40851111]
 [0.0521359  0.89219104 0.05567307]
 [0.44385547 0.15350955 0.40263498]]
[Epoch 55] log_likelihood: -2175.983 Delta: 0.05132
[[0.46644321 0.12545082 0.40810598]
 [0.05212008 0.89217031 0.0557096 ]
 [0.44394256 0.15379604 0.4022614 ]]
[Epoch 56] log_likelihood: -2175.9

[Epoch 101] log_likelihood: -2174.039 Delta: 0.02424
[[0.48294494 0.12181197 0.39524309]
 [0.05173903 0.89135433 0.05690664]
 [0.44468549 0.16343304 0.39188147]]
[Epoch 102] log_likelihood: -2174.016 Delta: 0.02345
[[0.48309438 0.12178226 0.39512336]
 [0.05173672 0.89134441 0.05691887]
 [0.444668   0.16353725 0.39179475]]
[Epoch 103] log_likelihood: -2173.993 Delta: 0.02268
[[0.48323725 0.12175385 0.3950089 ]
 [0.05173454 0.89133483 0.05693063]
 [0.44465045 0.16363771 0.39171184]]
[Epoch 104] log_likelihood: -2173.971 Delta: 0.02194
[[0.48337381 0.12172667 0.39489953]
 [0.05173249 0.89132559 0.05694193]
 [0.44463289 0.16373452 0.39163259]]
[Epoch 105] log_likelihood: -2173.950 Delta: 0.02121
[[0.48350427 0.12170067 0.39479505]
 [0.05173056 0.89131666 0.05695278]
 [0.44461534 0.16382779 0.39155687]]
[Epoch 106] log_likelihood: -2173.930 Delta: 0.02050
[[0.48362888 0.12167582 0.3946953 ]
 [0.05172874 0.89130805 0.05696321]
 [0.44459785 0.16391764 0.39148452]]
[Epoch 107] log_likelihood: 

[Epoch 152] log_likelihood: -2173.467 Delta: 0.00424
[[0.4859317  0.12119073 0.39287757]
 [0.05170317 0.89112064 0.05717619]
 [0.44404949 0.16584032 0.39011019]]
[Epoch 153] log_likelihood: -2173.462 Delta: 0.00410
[[0.48594666 0.12118712 0.39286623]
 [0.05170309 0.89111907 0.05717784]
 [0.44404321 0.16585624 0.39010055]]
[Epoch 154] log_likelihood: -2173.458 Delta: 0.00397
[[0.48596104 0.12118363 0.39285534]
 [0.05170302 0.89111754 0.05717944]
 [0.44403711 0.16587163 0.39009126]]
[Epoch 155] log_likelihood: -2173.455 Delta: 0.00384
[[0.48597486 0.12118026 0.39284488]
 [0.05170296 0.89111607 0.05718098]
 [0.44403118 0.16588651 0.39008231]]
[Epoch 156] log_likelihood: -2173.451 Delta: 0.00372
[[0.48598816 0.12117701 0.39283483]
 [0.05170289 0.89111464 0.05718246]
 [0.44402542 0.1659009  0.39007368]]
[Epoch 157] log_likelihood: -2173.447 Delta: 0.00360
[[0.48600096 0.12117387 0.39282517]
 [0.05170284 0.89111326 0.0571839 ]
 [0.44401982 0.16591482 0.39006536]]
[Epoch 158] log_likelihood: 

(array([[0.48627164, 0.12110453, 0.39262382],
        [0.05170204, 0.89108225, 0.05721571],
        [0.44388818, 0.16622699, 0.38988483]]),
 array([[9.99999689e-01, 3.10536462e-07],
        [9.31776192e-02, 9.06822381e-01],
        [9.05218782e-01, 9.47812181e-02]]),
 array([0.55569065, 0.44223769, 0.00207166]))